### PR TITLE
Updated indoor map example based on user feedback

### PR DESCRIPTION
**Pull request by hnativ13**

### CODE REVIEW

**Comment by dbacarel** [comment]
Hi @hnativ13, the diff shows changes that were already introduced in a previous commit. Could you please check that your branch is correctly rebased?

**Comment by hnativ13** [comment]
> Hi @hnativ13, the diff shows changes that were already introduced in a previous commit. Could you please check that your branch is correctly rebased?

Hello @dbacarel - it looks like the branch was rebased correctly, I'm not sure why my commit captured a commit from 11 November 2022. Do I need to remove this change that was already introduced in a previous commit from my pull request?

**Comment by dbacarel** [comment]
strange, in order to not mess up the history, would you mind creating a separate PR? I see that the changes are few and very minor

**Comment by hnativ13** [comment]
> strange, in order to not mess up the history, would you mind creating a separate PR? I see that the changes are few and very minor

Hi @dbacarel - sorry, this took me a little longer than I thought, but here it is - a separate PR: https://github.com/heremaps/maps-api-for-javascript-examples/pull/147

**Pull request closed without merging**
